### PR TITLE
Add sonar.login property at sonarscanner end

### LINKED ISSUE #2: Dotnet-sonar not working when sonar.login is used
Hi,

it seems that when using the dotnet-sonar plugin credentials can not be used.
I am passing my credentials like this (in build.gradle):

```
plugins {
	id 'com.itiviti.dotnet' version '1.3.6'
	id 'com.itiviti.dotnet-sonar' version '1.3.6'
}

dotnet {
	solution = '<myProject>.sln'
	configuration = 'Release'
}

sonarqube {
	properties {
		property 'sonar.host.url', <mySonarServerUrl>
		property 'sonar.login', <mySonarLogin>
		property 'sonar.projectKey', <projectKeyName>
		property 'sonar.branch', 'develop'
	}
}
```

However, when I call gradle with something like ```./gradlew clean build sonarqube -x dotnetTest -Pversion=1.0.0-SNAPSHOT``` I get this error:

```
> Task :sonarqube FAILED
Caching disabled for task ':sonarqube' because:
  Build cache is disabled
Task ':sonarqube' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'C:\workspace\<myProject>\build\dotnet\tools\dotnet-sonarscanner''. Working directory: C:\workspace\<myProject> Command: C:\workspace\<myProject>\build\dotnet\tools\dotnet-sonarscanner end
Successfully started process 'command 'C:\workspace\<myProject>\build\dotnet\tools\dotnet-sonarscanner''
SonarScanner for MSBuild 4.10
Using the .NET Core version of the Scanner for MSBuild
Post-processing started.
23:14:14.976  Credentials must be passed in both begin and end steps or not at all
23:14:14.976  Post-processing failed. Exit code: 1
```

Is there anything I can do about this?
I did not find anything about the end call in the code (I did not look very closely though)

Greetings,
Niko

### PR DESCRIPTION
**Pull request by ngyukman**
Fix #2

### CODE REVIEW

**Comment by nikolauskrismer** [comment]
I like your approach. Going ro close my PR then...
Can you take care about merging and building a new version?

**Comment by ngyukman** [comment]
@nikolauskrismer I have released 1.3.7 with the fix, can you have a try?
I don't have a sonar that require logon for testing

**Comment by NikoKrismerInnio** [comment]
Tested and works 👍🏼 

Somehow the anylsis itself does not yet work, but the login parameter does.
Can you give me a hint why my .cs files are not analysed (always show up as zero lines of code)

**Comment by ngyukman** [comment]
you might ask in sonar-dotnet with logs to see why it is not analysed 
It could be also the sonar‘s dotnet plugin is not updated

**Pull request merged**
