### PR TITLE
Add missing framework target for .NET6

### PR DESCRIPTION
**Pull request by KitsuneAlex**
'cause imma stupid ass.

### CODE REVIEW

**Comment by KitsuneAlex** [comment]
Oh, i think i broke your pipeline, sorry about that 😓

**Comment by ngyukman** [comment]
I think the problem is the azure pipeline is not yet with .net 6 installed

**Comment by KitsuneAlex** [comment]
Yeah i thought so, got it building with .NET6 on my local workstation no problems.

**Comment by KitsuneAlex** [comment]
Just giving this a little bump, not meaning to be annoying but i'd be pretty happy if this get's done >.>

**Comment by ngyukman** [comment]
I need to check how to get .net 6 into the azure pipeline, but we still have plenty of time before the official release of .net 6 :)

**Comment by KitsuneAlex** [comment]
Then tell me how to use a local build of the plugin at least :P Because i have that, i just can't seem to use for some reason, trying regular classpath dependency but with a file.

**Comment by ngyukman** [comment]
Hi @KitsuneAlex  if you want to use it locally, you can run `./gradlew publishToMavenLocal` and you will find it from your maven local (user profile/.m2/repository) with the version equals to the one in gradle.properties, you can put a version number like 1.8.0-SNAPSHOT, then you can use this version in your local build

**Comment by KitsuneAlex** [comment]
Oh yeah i know about local maven but i thought you could maybe include it as a jar with the project so other people can build my project too but i guess not, thanks anyways.

**Pull request merged**
